set(__QT_DEPLOY_TARGET_DbToolKitCore_FILE C:/Users/burak/Projects/desktop-apps/DbToolKit-Qt6/dbToolkit-qt/build-vs/Debug/DbToolKitCore.lib)
set(__QT_DEPLOY_TARGET_DbToolKitCore_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_DbToolKit_FILE C:/Users/burak/Projects/desktop-apps/DbToolKit-Qt6/dbToolkit-qt/build-vs/Debug/DbToolKit.exe)
set(__QT_DEPLOY_TARGET_DbToolKit_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_DbToolKit_RUNTIME_DLLS C:/Qt/6.11.1/mingw_64/bin/Qt6QuickControls2.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickTemplates2.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Quick.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6OpenGL.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlMeta.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlWorkerScript.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlModels.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Qml.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Network.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Core.dll)
